// sample js test



try {
    console.log("exception being tested")
    functionName();
} catch(error) {
    console.log("Service Unavailable")
}
